### ISSUE TITLE
BULK UPLOAD: Douala WorldPop (4 datasets)

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#201] opened 2019-08-22 20:33 UTC
These data and metadata are ready to be uploaded:
https://drive.google.com/drive/folders/1fqqpdl6LzJAwyKwfweuXaAGh2sTxX3Qg?usp=sharing

**Comment by kalxas** [comment] 2019-08-23 11:58
Is this a duplicate of https://github.com/state-hiu/2C-GeoNode/issues/195 ?

**Comment by kalxas** [comment] 2019-08-23 12:06
Not a duplicate after all, the upload has already happened, please review.

https://secondarycities.geonode.state.gov/layers/?limit=50&offset=0&order_by=-date

**Comment by kalxas** [comment] 2019-08-27 17:18
```
Finished processing 4 layers in 178.0 seconds.

4 Created layers
0 Updated layers
0 Skipped layers
0 Failed layers
44.500000 seconds per layer
```

**Comment by kalxas** [comment] 2019-08-27 17:18
```
Douala: Population 2010 (adjusted) : Metadata updated!
Douala: Population 2015 (adjusted) : Metadata updated!
Douala: Population 2010 : Metadata updated!
Douala: Population 2015 : Metadata updated!
```

**Comment by kalxas** [comment] 2019-09-12 19:47
This one also does not have errors reported, can we close?

**Closed as completed** 2019-09-12 20:03 UTC
Labels: data, needs review
