### ISSUE TITLE
Bulk Upload: Santiago GHSL

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#126] opened 2017-10-24 22:21 UTC
The Global Human Settlement Layer (GHSL) data and metadata for Santiago are ready to be uploaded.  Here's the link to the data and metadata: https://drive.google.com/open?id=0B2Oc3HZSI7QFazhqdEhXUkVOVFU

**Comment by sophialinn** [comment] 2017-11-03 14:13
This issue is redundant with issue #120

**Comment by kalxas** [comment] 2017-11-03 15:57
Closing as duplicate of #120

**Closed by kalxas** 2017-11-03 15:57 UTC
Labels: duplicate
