### ISSUE TITLE
BULK UPLOAD: GHSL Population Clipped to Bounding Box

### ISSUE THREAD

**Issue by sophialinn** [state-hiu/2C-GeoNode#195] opened 2019-07-31 15:53 UTC
The data and metadata in this folder are ready for upload. They are NEW datasets generated by 2C-CSU.

[https://drive.google.com/open?id=1frhb7RNevgCXX4FoqEzNr8q0NJ0H-ugi](url)

**Comment by kalxas** [comment] 2019-08-20 16:48
```
Finished processing 4 layers in 178.0 seconds.

4 Created layers
0 Updated layers
0 Skipped layers
0 Failed layers
44.500000 seconds per layer
```

**Comment by kalxas** [comment] 2019-08-20 16:51
```
douala: population 2010 (adjusted) : Failed to update
Exception: Layer matching query does not exist.
douala: population 2015 (adjusted) : Failed to update
Exception: Layer matching query does not exist.
Douala: Population 2010 : Metadata updated!
Douala: Population 2015 : Metadata updated!
```

**Comment by kalxas** [comment] 2019-08-20 17:04
Fixed 2 minor typos in the spreadsheet, now fixed:

```
Douala: Population 2010 (adjusted) : Metadata updated!
Douala: Population 2015 (adjusted) : Metadata updated!
Douala: Population 2010 : Metadata updated!
Douala: Population 2015 : Metadata updated!
```

**Comment by kalxas** [comment] 2019-08-20 17:05
Please review:
https://2c.puerti.co/layers/?limit=50&offset=0&order_by=-date

**Comment by arshores** [comment] 2019-08-20 21:46
Just looked at the layer. It downloads correctly. The imagery in the thumbnail doesn't look correct. That might be a different issue.

**Comment by kalxas** [comment] 2019-08-20 22:14
Regarding the thumbnails, this is related to making a nice raster style and updating it on GeoServer. 2 years ago we had such a process in place, so we can do something similar.

**Comment by kalxas** [comment] 2019-08-23 11:58
@sophialinn is this a duplicate of https://github.com/state-hiu/2C-GeoNode/issues/201?

I see the same files.

**Comment by kalxas** [comment] 2019-08-23 12:05
Looks like there was a mixup on my side and I uploaded the Douala folder on this ticket... Will reopen the ticket.

**Comment by kalxas** [comment] 2019-08-27 17:15
```
Finished processing 72 layers in 12514.0 seconds.

72 Created layers
0 Updated layers
0 Skipped layers
0 Failed layers
173.805556 seconds per layer
```

**Comment by kalxas** [comment] 2019-08-27 17:47
```
Boke: Population (1975 epoch) : Metadata updated!
Boke: Population (1990 epoch) : Metadata updated!
Boke: Population (2000 epoch) : Metadata updated!
Boke: Population (2015 epoch) : Metadata updated!
Cusco: Population (1975 epoch) : Metadata updated!
Cusco: Population (1990 epoch) : Metadata updated!
Cusco: Population (2000 epoch) : Metadata updated!
Cusco: Population (2015 epoch) : Metadata updated!
Darkhan: Population (1975 epoch) : Metadata updated!
Darkhan: Population (1990 epoch) : Metadata updated!
Darkhan: Population (2000 epoch) : Metadata updated!
Darkhan: Population (2015 epoch) : Metadata updated!
Denpasar: Population (1975 epoch) : Metadata updated!
Denpasar: Population (1990 epoch) : Metadata updated!
Denpasar: Population (2000 epoch) : Metadata updated!
denpasar: population (2015 epoch) : Failed to update
Exception: Layer matching query does not exist.
Douala: Population (1975 epoch) : Metadata updated!
Douala: Population (1990 epoch) : Metadata updated!
Douala: Population (2000 epoch) : Metadata updated!
Douala: Population (2015 epoch) : Metadata updated!
Esmeraldas: Population (1975 epoch) : Metadata updated!
Esmeraldas: Population (1990 epoch) : Metadata updated!
Esmeraldas: Population (2000 epoch) : Metadata updated!
Esmeraldas: Population (2015 epoch) : Metadata updated!
Guinea: Population (1975 epoch) : Metadata updated!
Guinea: Population (1990 epoch) : Metadata updated!
Guinea: Population (2000 epoch) : Metadata updated!
Guinea: Population (2015 epoch) : Metadata updated!
Indore: Population (1975 epoch) : Metadata updated!
Indore: Population (1990 epoch) : Metadata updated!
Indore: Population (2000 epoch) : Metadata updated!
Indore: Population (2015 epoch) : Metadata updated!
Kamsar: Population (1975 epoch) : Metadata updated!
Kamsar: Population (1990 epoch) : Metadata updated!
Kamsar: Population (2000 epoch) : Metadata updated!
Kamsar: Population (2015 epoch) : Metadata updated!
Kharkiv: Population (1975 epoch) : Metadata updated!
Kharkiv: Population (1990 epoch) : Metadata updated!
Kharkiv: Population (2000 epoch) : Metadata updated!
Kharkiv: Population (2015 epoch) : Metadata updated!
Medellin: Population (1975 epoch) : Metadata updated!
Medellin: Population (1990 epoch) : Metadata updated!
Medellin: Population (2000 epoch) : Metadata updated!
Medellin: Population (2015 epoch) : Metadata updated!
Mekelle: Population (1975 epoch) : Metadata updated!
Mekelle: Population (1990 epoch) : Metadata updated!
Mekelle: Population (2000 epoch) : Metadata updated!
Mekelle: Population (2015 epoch) : Metadata updated!
Pemba: Population (1975 epoch) : Metadata updated!
Pemba: Population (1990 epoch) : Metadata updated!
Pemba: Population (2000 epoch) : Metadata updated!
Pemba: Population (2015 epoch) : Metadata updated!
Pokhara: Population (1975 epoch) : Metadata updated!
Pokhara: Population (1990 epoch) : Metadata updated!
Pokhara: Population (2000 epoch) : Metadata updated!
Pokhara: Population (2015 epoch) : Metadata updated!
Port Harcourt: Population (1975 epoch) : Metadata updated!
Port Harcourt: Population (1990 epoch) : Metadata updated!
Port Harcourt: Population (2000 epoch) : Metadata updated!
Port Harcourt: Population (2015 epoch) : Metadata updated!
Santiago: Population (1975 epoch) : Metadata updated!
Santiago: Population (1990 epoch) : Metadata updated!
Santiago: Population (2000 epoch) : Metadata updated!
Santiago: Population (2015 epoch) : Metadata updated!
Santa Fe: Population (1975 epoch) : Metadata updated!
Santa Fe: Population (1990 epoch) : Metadata updated!
Santa Fe: Population (2000 epoch) : Metadata updated!
Santa Fe: Population (2015 epoch) : Metadata updated!
Tijuana: Population (1975 epoch) : Metadata updated!
Tijuana: Population (1990 epoch) : Metadata updated!
Tijuana: Population (2000 epoch) : Metadata updated!
Tijuana: Population (2015 epoch) : Metadata updated!
```

**Comment by sophialinn** [comment] 2019-09-12 20:05
Only one failed metadata update: denpasar: population (2015 epoch)

**Comment by kalxas** [comment] 2019-09-12 20:05
This one seems fine now, the Denpasar population layer for 2015 has metadata:

https://secondarycities.geonode.state.gov/layers/idn_ppp_v2b_2015_unadj#/

**Closed as completed** 2019-09-12 20:22 UTC
Labels: data, needs review
